### ISSUE TITLE
Error: Target label does not exist. (Specifically: gTest)

### ISSUE THREAD

**Issue by jbrundage** [Obyruz/TT2-AHK#1]
This error appears when running `TapTitans2-Bot.ahk`

![image](https://user-images.githubusercontent.com/1891935/36067647-fcf3c2a2-0e8e-11e8-8a50-a6139111ecfa.png)

**Comment by jbrundage** [comment]
Looks like the `Test` function doesn't exist. Removing that line fixes the issue.

**Comment by Obyruz** [comment]
You are correct, I must've forgotten it in there while trying to add a new functionality. I have fixed this issue and adjusted the code to fix the new valentine's fairy.
Thank you for your help.
